---
- name: tasks
  hosts: clients
  become: true

  tasks:
  - name: create a user
    user:
      name: "Ron"
      password: "Aa123456"

  - name: Create multiple users
    user:
      name: "{{ item }}"
    loop:
    - Ron
    - Harry
    - hermione

  - name: Check if there is enough memory
    debug:
      msg: "not enough memory"
    when: ansible_memtotal_mb < 256

  - name: run joke script
    script: /root/ansible/joke.sh
    register: joke 
    when: ansible_memtotal_mb > 256

  - name: print joke output
    debug:
      msg: "{{joke.stdout}}"

