---
- name: copy the binary to {{ exporter_binary_dest }}
  copy:
    src: "{{ exporter_binary }}"
    dest: "{{ exporter_binary_dest }}"

    mode: 0755

- name: put systemd service file in place
  copy:
    src: "{{ exporter_service }}"
    dest: "{{ exporter_service_dest }}"


#- name: copy the upstart conf to {{ exporter_upstart_dest }}
#  copy:
#    src: "{{ exporter_upstart }}"
#    dest: "{{ exporter_upstart_dest }}"


- name: update systemd and restart exporter systemd
  systemd:
    daemon-reload: true
    enabled: true
    state: restarted
    name: "prometheus-node-exporter.service"

   
- name: start exporter sysv service
  service:
    name: "prometheus-node-exporter.service"
    enabled: true
    state: restarted

- name: open port 9100 traffic
  ansible.posix.firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
  notify:
    - restart firewalld