---
- name: tasks
  become: true
  hosts: clients
  vars_files:
  - var-file.yml
  tasks:
  - name: run postgres
    containers.podman.podman_container:
      name: postgres
      image: docker.io/postgres
      ports:
      - "5432:5432"
      env:
        POSTGRES_PASSWORD: "{{ {{ password  }} | password_hash('sha512') }}"
  - name: Execute command
    containers.podman.podman_container_exec:
      name: postgres
      command: "cat redhat-release"
      workdir: /etc


