---
- name: POSTGRES
  hosts: postgres
  vars_files:
  - vault.yaml
  tasks:
  - name: Create Postgres Container
    containers.podman.podman_container:
      name: postgres
      image: docker.io/postgres
      ports:
      - "5432:5432"
      env:
        POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
  - name: Register Postgres Version
    register: pg_version
    containers.podman.podman_container_exec:
      name: postgres
      command: "psql --version"
  - name: Print Postgres Version
    debug:
      msg: "{{ pg_version.stdout }}"
